Reduce Alert Spam
wisdom-oss/service-swat-collector pull request #1
Opened 2024-01-31 15:54 UTC by cptpiepmatz

This PR changes the behavior of sending an alert into our alert channel. It is done by only sending an alert when a request failed and then only again when all requests went through. Also it groups multiple fails into one alert message.

2024-01-31 16:10 UTC, dr4hcu5-jan requested changes

2024-01-31 16:10 UTC, dr4hcu5-jan commented on src/webhook.rs
> +            .description("Some errors occurred.\nWe notify again when everything is green again.");
The description does not sound right and using colors to describe a status feels wrong in a text.

```suggestion
            .description("Some errors occurred.\nAs soon as all requests are successful again you will be notified.");
```

2024-01-31 16:10 UTC, dr4hcu5-jan commented on src/webhook.rs
> +            .description("Every request was successful.");
This message only shows that every request was successful but does not explain that the collector works as expected again
```suggestion
            .description("All requests have been successful. Collector working as expected again.");
```

2024-01-31 16:17 UTC, cptpiepmatz commented
I accidentally committed one code suggestion with a wrong commit message. 🙃

2024-02-01 10:17 UTC, dr4hcu5-jan approved these changes

2024-02-01 10:18 UTC, merged